apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvmi2
spec:
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: disk0
      - disk:
          bus: virtio
        name: disk1
      interfaces:
      - masquerade: {}
        name: default
      rng: {}
    features:
      acpi:
        enabled: true
    machine:
      type: q35
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-sriov-lane-container-disk:devel
      #imagePullPolicy: IfNotPresent
      imagePullPolicy: Always
    name: disk0
  - cloudInitNoCloud:
      userData: "#!/bin/bash\n\techo \"fedora\" |passwd fedora --stdin\n\techo "
    name: disk1
