apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvmi1
spec:
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: disk0
      - disk:
          bus: virtio
        name: disk1
      interfaces:
      - masquerade: {}
        name: default
      rng: {}
    features:
      acpi:
        enabled: true
    firmware:
      uuid: e1731895-c741-4845-8498-c366dd06f1ab
    machine:
      type: q35
    resources:
      requests:
        cpu: 100m
        memory: 512M
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-sriov-lane-container-disk-test:devel
      imagePullPolicy: IfNotPresent
    name: disk0
  - cloudInitNoCloud:
      networkData: |
        version: 2
      userData: "#!/bin/bash\n\trm -f /var/lib/cloud/instance/boot-finished\n\techo "
    name: disk1
