apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvmi
spec:
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: disk0
      interfaces:
      - masquerade: {}
        name: default
      - name: sriov
        sriov: {}
      rng: {}
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 832e297d-ede2-46bc-9bce-524d24aa2503
    machine:
      type: q35
    resources:
      requests:
        cpu: 100m
        memory: 1024M
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: sriov
    name: sriov
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-sriov-lane-container-disk:devel
      imagePullPolicy: IfNotPresent
    name: disk0
